namespace AutoMapperVsManual
{
    public class Dest
    {
        public int S1 { get; set; }
        public int S2 { get; set; }
        public int S3 { get; set; }
        public int S4 { get; set; }
        public int S5 { get; set; }
        public int S6 { get; set; }
        public int S7 { get; set; }
        public int S8 { get; set; }
        public int S9 { get; set; }
        public int S10 { get; set; }
        public int S11 { get; set; }
        public int S12 { get; set; }
        public int S13 { get; set; }
        public int S14 { get; set; }
        public int S15 { get; set; }
        public int S16 { get; set; }
        public int S17 { get; set; }
        public int S18 { get; set; }
        public int S19 { get; set; }
        public int S20 { get; set; }
        public int S21 { get; set; }
        public int S22 { get; set; }
        public int S23 { get; set; }
        public int S24 { get; set; }
        public int S25 { get; set; }
        public int S26 { get; set; }
        public int S27 { get; set; }
        public int S28 { get; set; }
        public int S29 { get; set; }
        public int S30 { get; set; }
        public int S31 { get; set; }
        public int S32 { get; set; }
        public int S33 { get; set; }
        public int S34 { get; set; }
        public int S35 { get; set; }
        public int S36 { get; set; }
        public int S37 { get; set; }
        public int S38 { get; set; }
        public int S39 { get; set; }
        public int S40 { get; set; }
        public int S41 { get; set; }
        public int S42 { get; set; }
        public int S43 { get; set; }
        public int S44 { get; set; }
        public int S45 { get; set; }
        public int S46 { get; set; }
        public int S47 { get; set; }
        public int S48 { get; set; }
        public int S49 { get; set; }
        public int S50 { get; set; }
        public int S51 { get; set; }
        public int S52 { get; set; }
        public int S53 { get; set; }
        public int S54 { get; set; }
        public int S55 { get; set; }
        public int S56 { get; set; }
        public int S57 { get; set; }
        public int S58 { get; set; }
        public int S59 { get; set; }
        public int S60 { get; set; }
        public int S61 { get; set; }
        public int S62 { get; set; }
        public int S63 { get; set; }
        public int S64 { get; set; }
        public int S65 { get; set; }
        public int S66 { get; set; }
        public int S67 { get; set; }
        public int S68 { get; set; }
        public int S69 { get; set; }
        public int S70 { get; set; }
        public int S71 { get; set; }
        public int S72 { get; set; }
        public int S73 { get; set; }
        public int S74 { get; set; }
        public int S75 { get; set; }
        public int S76 { get; set; }
        public int S77 { get; set; }
        public int S78 { get; set; }
        public int S79 { get; set; }
        public int S80 { get; set; }
        public int S81 { get; set; }
        public int S82 { get; set; }
        public int S83 { get; set; }
        public int S84 { get; set; }
        public int S85 { get; set; }
        public int S86 { get; set; }
        public int S87 { get; set; }
        public int S88 { get; set; }
        public int S89 { get; set; }
        public int S90 { get; set; }
        public int S91 { get; set; }
        public int S92 { get; set; }
        public int S93 { get; set; }
        public int S94 { get; set; }
        public int S95 { get; set; }
        public int S96 { get; set; }
        public int S97 { get; set; }
        public int S98 { get; set; }
        public int S99 { get; set; }
        public int S100 { get; set; }
    }
}
